const Movies = [
    {
        adult: false,
        backdrop_path: "/eTp97yGiUiphRYtICwAgV6mghP6.jpg",
        id: 359412,
        original_language: "en",
        original_title: "Marauders",
        overview: "An untraceable group of elite bank robbers is chased by a suicidal FBI agent who uncovers a deeper purpose behind the robbery-homicides.",
        popularity: 17.718,
        poster_path: "/bAvmDn5C7arBoRrfaG3b3Kdue1q.jpg",
        release_date: "2016-07-01",
        title: "Marauders",
        video: false,
        vote_average: 5.8
    },
    {
        adult: false,
        backdrop_path: "/8b4vDh7hNSLZKyAYUnZJalExbJb.jpg",
        id: 388,
        original_language: "en",
        original_title: "Inside Man",
        overview: "When an armed, masked gang enter a Manhattan bank, lock the doors and take hostages, the detective assigned to effect their release enters negotiations preoccupied with corruption charges he is facing.",
        popularity: 15.801,
        poster_path: "/mf4i9zZVXMmqWsEb9D0OAY7k3t.jpg",
        release_date: "2006-03-17",
        title: "Inside Man",
        video: false,
        vote_average: 7.4,
        vote_count: 4086,
    },
    {
        adult: false,
        backdrop_path: "/7KGY8HYvwmJwMFMy0hFqp7eiycF.jpg",
        genre_ids: (4)[28, 80, 18, 53],
        id: 507,
        original_language: "en",
        original_title: "Killing Zoe",
        overview: "Zed is an American vault-cracker who travels to Paris to meet up with his old friend Eric. Eric and his gang have planned to raid the only bank in the city which is open on Bastille day. After offering his services, Zed soon finds himself trapped in a situation beyond his control when heroin abuse, poor planning and a call-girl named Zoe all conspire to turn the robbery into a very bloody siege.",
        popularity: 9.902,
        poster_path: "/k3UEKMVnkljOlsO5sLmz87YGlaG.jpg",
        release_date: "1993-10-01",
        title: "Killing Zoe",
        video: false,
        vote_average: 6.3,
    },
    {
        adult: false,
        backdrop_path: "/66sGdfAPFQwIiQrJoHbRfxZsZM3.jpg",
        genre_ids: (2)[35, 80],
        id: 10569,
        original_language: "en",
        original_title: "Small Time Crooks",
        overview: "A loser of a crook and his wife strike it rich when a botched bank job's cover business becomes a spectacular success.",
        popularity: 12.556,
        poster_path: "/eIJRFZFDmh0xXPlKt3WwN5fiSLe.jpg",
        release_date: "2000-05-19",
        title: "Small Time Crooks",
        video: false,
        vote_average: 6.5,
        vote_count: 435,
    },
];

export default Movies;